### ISSUE TITLE
Can't compile it in Debian

### ISSUE THREAD

**Issue by LucasEsposito** [aerror2/ILSpy-For-MacOSX#4]
Hi,

I'm having trouble compiling the source code in debian stretch using mono. Currently I'm using a docker image for Debian. As I'm using docker, I can't use GUI apps, so it's not possible for me to follow the steps in the readme.

Here is the output of some of the commands I tried. It's the first time I use mono so I'm not sure whether I'm doing it correctly or not.

root@06e3e39cc06d:/tmpfs/ILSpy-For-MacOSX# mcs ILSpyMac.sln -sdk:4 
```
ILSpyMac.sln(2,0): error CS1525: Unexpected symbol `Microsoft'
ILSpyMac.sln(4,0): error CS1024: Wrong preprocessor directive
ILSpyMac.sln(4,78): error CS1009: Unrecognized escape sequence `\M'
ILSpyMac.sln(6,90): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(6,113): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(8,97): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(8,127): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(10,102): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(12,74): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(174,17): error CS1009: Unrecognized escape sequence `\I'

```

root@06e3e39cc06d:/tmpfs/ILSpy-For-MacOSX# mcs ILSpyMac.sln
```
ILSpyMac.sln(2,0): error CS1525: Unexpected symbol `Microsoft'
ILSpyMac.sln(4,0): error CS1024: Wrong preprocessor directive
ILSpyMac.sln(4,78): error CS1009: Unrecognized escape sequence `\M'
ILSpyMac.sln(6,90): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(6,113): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(8,97): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(8,127): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(10,102): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(12,74): error CS1009: Unrecognized escape sequence `\I'
ILSpyMac.sln(174,17): error CS1009: Unrecognized escape sequence `\I'
Compilation failed: 10 error(s), 0 warnings
root@06e3e39cc06d:/tmpfs/ILSpy-For-MacOSX# 
```

xbuild
```
XBuild Engine Version 14.0
Mono, Version 4.6.2.0
Copyright (C) 2005-2013 Various Mono authors

Build started 11/15/2017 22:30:57.
__________________________________________________
Project "/tmpfs/ILSpy-For-MacOSX/ILSpyMac.sln" (default target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "Debug|x86".
        Target Build:
                Project "/tmpfs/ILSpy-For-MacOSX/Mono.Cecil/Mono.Cecil.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: net_2_0_Debug Platform: AnyCPU
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target CoreCompile:
                        Skipping target "CoreCompile" because its outputs are up-to-date.
                Done building project "/tmpfs/ILSpy-For-MacOSX/Mono.Cecil/Mono.Cecil.csproj".
                Project "/tmpfs/ILSpy-For-MacOSX/NRefactory/ICSharpCode.NRefactory/ICSharpCode.NRefactory.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Debug Platform: AnyCPU
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target _GenerateTargetFrameworkMonikerAttribute:
                        Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
                        Target CoreCompile:
                                Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /delaysign- /debug+ /keyfile:../ICSharpCode.NRefactory.snk /optimize- /out:obj/Debug/ICSharpCode.NRefactory.dll Analysis/AbiComparer.cs Analysis/TypeGraph.cs Analysis/TypeGraphNode.cs Documentation/DocumentationComment.cs Documentation/GetPotentiallyNestedClassTypeReference.cs Documentation/IDocumentationProvider.cs Editor/IDocument.cs Editor/IDocumentLine.cs Editor/ISegment.cs Editor/ITextAnchor.cs Editor/ITextSource.cs Editor/ReadOnlyDocument.cs Editor/StringBuilderDocument.cs Editor/StringTextSource.cs Editor/TextChangeEventArgs.cs Editor/TextSourceVersionProvider.cs IAnnotatable.cs PatternMatching/BacktrackingInfo.cs PatternMatching/Choice.cs PatternMatching/AnyNode.cs PatternMatching/Backreference.cs PatternMatching/INode.cs PatternMatching/Match.cs PatternMatching/NamedNode.cs PatternMatching/OptionalNode.cs PatternMatching/Repeat.cs PatternMatching/Pattern.cs Documentation/XmlDocumentationProvider.cs Properties/AssemblyInfo.cs Properties/GlobalAssemblyInfo.cs Role.cs Semantics/AmbiguousResolveResult.cs Semantics/ArrayAccessResolveResult.cs Semantics/ArrayCreateResolveResult.cs Semantics/ByReferenceResolveResult.cs Semantics/ConstantResolveResult.cs Semantics/ConversionResolveResult.cs Semantics/SizeOfResolveResult.cs Semantics/ErrorResolveResult.cs Semantics/Conversion.cs Semantics/ForEachResolveResult.cs Semantics/InitializedObjectResolveResult.cs Semantics/InvocationResolveResult.cs Semantics/LocalResolveResult.cs Semantics/MemberResolveResult.cs Semantics/NamedArgumentResolveResult.cs Semantics/NamespaceResolveResult.cs Semantics/OperatorResolveResult.cs Semantics/ResolveResult.cs Semantics/ThisResolveResult.cs Semantics/TypeIsResolveResult.cs Semantics/TypeOfResolveResult.cs Semantics/TypeResolveResult.cs Semantics/UnknownMemberResolveResult.cs TextLocation.cs TypeSystem/Accessibility.cs TypeSystem/AnonymousType.cs TypeSystem/ArrayType.cs TypeSystem/AssemblyQualifiedTypeName.cs TypeSystem/ByReferenceType.cs TypeSystem/ComHelper.cs TypeSystem/DefaultSolutionSnapshot.cs TypeSystem/DomRegion.cs TypeSystem/EntityType.cs TypeSystem/ICodeContext.cs TypeSystem/Implementation/BlobReader.cs TypeSystem/Implementation/DefaultVariable.cs TypeSystem/Implementation/ResolvedAttributeBlob.cs TypeSystem/Implementation/UnresolvedAttributeBlob.cs TypeSystem/Implementation/UnresolvedSecurityDeclarationBlob.cs TypeSystem/ISymbol.cs TypeSystem/TaskType.cs TypeSystem/TypeParameterSubstitution.cs TypeSystem/TypeSystemExtensions.cs TypeSystem/FullTypeName.cs TypeSystem/IAmbience.cs TypeSystem/IAssembly.cs TypeSystem/IAttribute.cs TypeSystem/ICompilation.cs TypeSystem/IConstantValue.cs TypeSystem/IEntity.cs TypeSystem/IEvent.cs TypeSystem/IField.cs TypeSystem/IFreezable.cs TypeSystem/IInterningProvider.cs TypeSystem/IMember.cs TypeSystem/IMethod.cs TypeSystem/Implementation/AbstractFreezable.cs TypeSystem/Implementation/AbstractResolvedEntity.cs TypeSystem/Implementation/AbstractResolvedMember.cs TypeSystem/Implementation/AbstractResolvedTypeParameter.cs TypeSystem/Implementation/AbstractType.cs TypeSystem/Implementation/AbstractUnresolvedEntity.cs TypeSystem/Implementation/AbstractUnresolvedMember.cs TypeSystem/Implementation/AccessorOwnerMemberReference.cs TypeSystem/Implementation/BaseTypeCollector.cs TypeSystem/Implementation/DefaultAssemblyReference.cs TypeSystem/Implementation/DefaultAttribute.cs TypeSystem/Implementation/DefaultMemberReference.cs TypeSystem/Implementation/DefaultParameter.cs TypeSystem/Implementation/DefaultResolvedEvent.cs TypeSystem/Implementation/DefaultResolvedField.cs TypeSystem/Implementation/DefaultResolvedMethod.cs TypeSystem/Implementation/DefaultResolvedProperty.cs TypeSystem/Implementation/DefaultResolvedTypeDefinition.cs TypeSystem/Implementation/DefaultResolvedTypeParameter.cs TypeSystem/Implementation/DefaultUnresolvedAssembly.cs TypeSystem/Implementation/DefaultUnresolvedAttribute.cs TypeSystem/Implementation/DefaultUnresolvedEvent.cs TypeSystem/Implementation/DefaultUnresolvedField.cs TypeSystem/Implementation/DefaultUnresolvedMethod.cs TypeSystem/Implementation/DefaultUnresolvedParameter.cs TypeSystem/Implementation/DefaultUnresolvedProperty.cs TypeSystem/Implementation/DefaultUnresolvedTypeDefinition.cs TypeSystem/Implementation/DefaultUnresolvedTypeParameter.cs TypeSystem/Implementation/DummyTypeParameter.cs TypeSystem/Implementation/ExplicitInterfaceImplementationMemberReference.cs TypeSystem/Implementation/FullNameAndTypeParameterCount.cs TypeSystem/Implementation/GetClassTypeReference.cs TypeSystem/Implementation/GetMembersHelper.cs TypeSystem/Implementation/KnownTypeCache.cs TypeSystem/Implementation/MergedNamespace.cs TypeSystem/Implementation/MinimalCorlib.cs TypeSystem/Implementation/NestedTypeReference.cs TypeSystem/Implementation/SimpleCompilation.cs TypeSystem/Implementation/SimpleConstantValue.cs TypeSystem/Implementation/SimpleInterningProvider.cs TypeSystem/Implementation/SpecializedEvent.cs TypeSystem/Implementation/SpecializedField.cs TypeSystem/Implementation/SpecializedMember.cs TypeSystem/Implementation/SpecializedMethod.cs TypeSystem/Implementation/SpecializedProperty.cs TypeSystem/Implementation/SpecializingMemberReference.cs TypeSystem/Implementation/TypeParameterReference.cs TypeSystem/Implementation/TypeWithElementType.cs TypeSystem/Implementation/UnknownType.cs TypeSystem/Implementation/VoidTypeDefinition.cs TypeSystem/INamedElement.cs TypeSystem/INamespace.cs TypeSystem/InheritanceHelper.cs TypeSystem/IntersectionType.cs TypeSystem/IParameter.cs TypeSystem/IParameterizedMember.cs TypeSystem/IUnresolvedFile.cs TypeSystem/IProjectContent.cs TypeSystem/IProperty.cs TypeSystem/ISolutionSnapshot.cs TypeSystem/ISupportsInterning.cs TypeSystem/IType.cs TypeSystem/ITypeDefinition.cs TypeSystem/ITypeParameter.cs TypeSystem/ITypeReference.cs TypeSystem/KnownTypeReference.cs TypeSystem/NullableType.cs TypeSystem/ParameterizedType.cs TypeSystem/ParameterListComparer.cs TypeSystem/ProjectReference.cs TypeSystem/ReflectionNameParseException.cs TypeSystem/SimpleTypeResolveContext.cs TypeSystem/TopLevelTypeName.cs TypeSystem/TypeKind.cs TypeSystem/TypeVisitor.cs TypeSystem/IVariable.cs TypeSystem/PointerType.cs TypeSystem/ReflectionHelper.cs TypeSystem/SpecialType.cs Utils/7BitEncodedInts.cs Utils/BitVector16.cs Utils/BusyManager.cs Utils/CacheManager.cs Utils/CallbackOnDispose.cs Utils/CSharpPrimitiveCast.cs Utils/EmptyList.cs Utils/ExtensionMethods.cs Utils/FastSerializer.cs Utils/GraphVizGraph.cs Utils/ImmutableStack.cs Utils/KeyComparer.cs Utils/LazyInit.cs Utils/MultiDictionary.cs Utils/Platform.cs Utils/ProjectedList.cs Utils/ReferenceComparer.cs Utils/TreeTraversal.cs TypeSystem/Error.cs Completion/ICompletionData.cs Completion/DisplayFlags.cs Completion/IEntityCompletionData.cs Completion/CompletionCategory.cs Completion/IParameterDataProvider.cs Completion/IVariableCompletionData.cs Documentation/IdStringProvider.cs Documentation/IdStringMemberReference.cs Utils/CompositeFormatStringParser/CompositeFormatStringParser.cs Utils/CompositeFormatStringParser/TextSegment.cs Utils/CompositeFormatStringParser/FormatItem.cs Utils/CompositeFormatStringParser/FormatStringSegmentBase.cs Utils/CompositeFormatStringParser/IFormatStringSegment.cs Utils/CompositeFormatStringParser/IFormatStringError.cs Completion/CompletionExtensionMethods.cs Refactoring/IssueMarker.cs Refactoring/Severity.cs Analysis/SymbolCollector.cs TypeSystem/AssemblyLoader.cs Editor/UnicodeNewline.cs Completion/FrameworkLookup.cs Utils/ComparableList.cs PatternMatching/AnyNodeOrNull.cs Editor/ITextPasteHandler.cs obj/Debug/.NETFramework,Version=v4.0.AssemblyAttribute.cs /target:library /warnaserror- /unsafe- /checked+ /define:"DEBUG;TRACE" /nowarn:1591 /doc:../bin/Debug/ICSharpCode.NRefactory.xml /nostdlib /platform:AnyCPU /reference:/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll /reference:/usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll /reference:/usr/lib/mono/gac/System.Xml.Linq/4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll /reference:/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll /warn:4
CSC: error CS0518: The predefined type `System.Object' is not defined or imported
CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
CSC: error CS0518: The predefined type `System.Single' is not defined or imported
CSC: error CS0518: The predefined type `System.Double' is not defined or imported
CSC: error CS0518: The predefined type `System.Char' is not defined or imported
CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
CSC: error CS0518: The predefined type `System.String' is not defined or imported
CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
CSC: error CS0518: The predefined type `System.Void' is not defined or imported
CSC: error CS0518: The predefined type `System.Array' is not defined or imported
CSC: error CS0518: The predefined type `System.Type' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
                        Task "Csc" execution -- FAILED
                        Done building target "CoreCompile" in project "/tmpfs/ILSpy-For-MacOSX/NRefactory/ICSharpCode.NRefactory/ICSharpCode.NRefactory.csproj".-- FAILED
                Done building project "/tmpfs/ILSpy-For-MacOSX/NRefactory/ICSharpCode.NRefactory/ICSharpCode.NRefactory.csproj".-- FAILED
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "/tmpfs/ILSpy-For-MacOSX/ILSpyMac.sln".-- FAILED
Done building project "/tmpfs/ILSpy-For-MacOSX/ILSpyMac.sln".-- FAILED

Build FAILED.
Errors:

/tmpfs/ILSpy-For-MacOSX/ILSpyMac.sln (default targets) ->
(Build target) ->
/tmpfs/ILSpy-For-MacOSX/NRefactory/ICSharpCode.NRefactory/ICSharpCode.NRefactory.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

        CSC: error CS0518: The predefined type `System.Object' is not defined or imported
        CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
        CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
        CSC: error CS0518: The predefined type `System.Single' is not defined or imported
        CSC: error CS0518: The predefined type `System.Double' is not defined or imported
        CSC: error CS0518: The predefined type `System.Char' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
        CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
        CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
        CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
        CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
        CSC: error CS0518: The predefined type `System.String' is not defined or imported
        CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
        CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
        CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
        CSC: error CS0518: The predefined type `System.Void' is not defined or imported
        CSC: error CS0518: The predefined type `System.Array' is not defined or imported
        CSC: error CS0518: The predefined type `System.Type' is not defined or imported
        CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
        CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
        CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
        CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
        CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
        CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
        CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
        CSC: error CS0518: The predefined type `System.Exception' is not defined or imported

         0 Warning(s)
         31 Error(s)

Time Elapsed 00:00:01.9361750
```
